services:
  alertmanager:
    container_name: aalert
    image: prom/alertmanager:v0.24.0
    ports:
      - 9093:9093
    volumes:
      - ./prometheus/rule_config.yml:/etc/alertmanager/config.yml
    networks:
      - scylla-network
  grafana:
    container_name: agraf
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=scylladb-scylla-datasource
      # This is where you set Grafana security
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # To set your home dashboard uncomment the following line, set VERSION to be your current version
    #- GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/ver_VERSION/scylla-overview.VERSION.json
    image: grafana/grafana:9.3.11
    ports:
      - 3000:3000
    user: 1000:1000
    volumes:
      - ./grafana/build:/var/lib/grafana/dashboards
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/provisioning:/var/lib/grafana/provisioning
    # Uncomment the following line for grafana persistency
    # - path/to/grafana/dir:/var/lib/grafana
    networks:
      - scylla-network
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    container_name: aprom
    image: prom/prometheus:v2.42.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/build/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/scylla_servers.yml:/etc/scylla.d/prometheus/targets/scylla_servers.yml
      - ./prometheus/prom_rules/:/etc/prometheus/prom_rules/
      - ./prometheus/scylla_manager_servers.yml:/etc/scylla.d/prometheus/targets/scylla_manager_servers.yml
      - ./prometheus/scylla_servers.yml:/etc/scylla.d/prometheus/targets/node_exporter_servers.yml
    # Uncomment the following line for prometheus persistency
    # - path/to/data/dir:/prometheus/data
    networks:
      - scylla-network
networks:
  scylla-network:
    driver: bridge
    external: true
    name: "scylla-network"
version: "3"
